medium:
  account:
    integration-token:
    author-id:
  content-format: markdown
  tags:
  publish-status: public
  canonical-url:
  file:
  file-path:
  api-base-url: https://api.medium.com/v1/users/<userId>/posts
